# -*- coding: utf-8 -*-
"""lab02-BestFirstSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jQzyRuo_-RsLQjxS-rk3SZMcPlZItj3I

Course: **Introduction to Artificial Intelligence** \
Lecturer: **Nguyen Thanh An** \
Lab 02: **Best First Search**

Students implement GBFS and A* algorithms following TODO 1 - 2. \
Students can add supporting attributes and methods to the two classes as needed.

# Libraries
"""

import os
import heapq

"""# Graph class"""

# Directed, weighted graphs
class Graph:
  def __init__(self):
    self.AL = dict() # adjacency list
    self.V = 0
    self.E = 0
    self.H = dict()

  def __str__(self):
    res = 'V: %d, E: %d\n'%(self.V, self.E)
    for u, neighbors in self.AL.items():
      line = '%d: %s\n'%(u, str(neighbors))
      res += line
    for u, h in self.H.items():
      line = 'h(%d) = %d\n'%(u, h)
    return res

  def print(self):
    print(str(self))

  def load_from_file(self, filename):
    '''
        Example input file:
            V E
            u v w
            u v w
            u v w
            ...
            u1 h1
            u2 h2
            u3 h3
            ...

        # input.txt
        7 8
        0 1 5 
        0 2 6
        1 3 12
        1 4 9
        2 5 5
        3 5 8
        3 6 7
        4 6 4
        0 14
        1 13
        2 12
        3 11
        4 10
        5 9
        6 0
    '''
    if os.path.exists(filename):
      with open(filename) as g:
        self.V, self.E = [int(it) for it in g.readline().split()]
        for i in range(self.E):
          line = g.readline()
          u, v, w = [int(it) for it in line.strip().split()]
          if u not in self.AL:
            self.AL[u] = []
          self.AL[u].append((v, w))
        for i in range(self.V):
          line = g.readline()
          u, h = [int(it) for it in line.strip().split()]
          self.H[u] = h

g = Graph()
g.load_from_file('input.txt')
g.print()





"""# Search Strategies"""

class BestSearchStrategy:
  def search(self, g: Graph, src: int, dst: int) -> tuple:
    expanded = [] # list of expanded vertices in the traversal order
    path = [] # path from src to dst
    return expanded, pathc

class GBFS(BestSearchStrategy):
  def search(self, g: Graph, src: int, dst: int) -> tuple:
    expanded = [] # list of expanded vertices in the traversal order
    path = [] # path from src to dst

    pq = [] # priority queue of vertices to expand
    heapq.heappush(pq, (g.H[src], src))
    parent = {} # dictionary to store the parent of each vertex in the search tree

    while pq:
      curr_h, curr = heapq.heappop(pq) # get the vertex with the lowest heuristic value
      expanded.append(curr) # mark the vertex as expanded

      if curr == dst:
        # we have found the destination, so backtrack to get the path
        while curr in parent:
          path.insert(0, curr)
          curr = parent[curr]
        path.insert(0, curr) # add the source vertex to the path
        break
      for neighbor, weight in g.AL.get(curr,[]):
        if neighbor not in expanded:
          # push unexpanded neighbors to the priority queue with their heuristic value as priority
          heapq.heappush(pq, (g.H[neighbor], neighbor))
          parent[neighbor] = curr # update the parent of the neighbor

    return expanded, path

class AStar(BestSearchStrategy):
   def search(self, g: Graph, src: int, dst: int) -> tuple:
    expanded = [] # list of expanded vertices in the traversal order
    path = [] # path from src to dst
    pq = [] # priority queue of vertices to expand
    heapq.heappush(pq, (g.H[src], src)) # push the source node with its heuristic value
    parent = {} # dictionary to store the parent of each vertex in the search tree
    g_score = {src: 0} # dictionary to store the g-score (cost so far) of each vertex

    while pq:
      curr_h, curr = heapq.heappop(pq) # get the vertex with the lowest f-score
      expanded.append(curr) # mark the vertex as expanded

      if curr == dst:
        # we have found the destination, so backtrack to get the path
        while curr in parent:
          path.insert(0, curr)
          curr = parent[curr]
        path.insert(0, curr) # add the source vertex to the path
        break

      for neighbor, weight in g.AL.get(curr,[]):
        g_new = g_score[curr] + weight # calculate the new g-score for the neighbor
        if neighbor not in g_score or g_new < g_score[neighbor]:
          # update the g-score and parent of the neighbor
          g_score[neighbor] = g_new
          parent[neighbor] = curr
          f_new = g_new + g.H[neighbor] # calculate the new f-score for the neighbor
          heapq.heappush(pq, (f_new, neighbor)) # push the neighbor with its f-score to the priority queue

    return expanded, path

"""# Evaluation"""

gbfs = GBFS()
astar = AStar()

for stg in [gbfs, astar]:
  print(stg)
  expanded, path = stg.search(g, 0, g.V-1)
  print(expanded)
  print(path)

""" # Submission Notice


*   Maintain all cell outputs
*   Download and rename the notebook as **lab02_\<Student ID\>.ipynb**
*   Submit by the deadline

"""